<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.esa.cci.wv</groupId>
        <artifactId>wv-cci-parent</artifactId>
        <version>5.0-SNAPSHOT</version>
    </parent>

    <artifactId>snap-tcwv</artifactId>
    <packaging>nbm</packaging>

    <name>WaterVapour-CCI for SNAP</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <!--<snap.version>6.0.0</snap.version>-->
        <!--<snap.version>7.0.0-SNAPSHOT</snap.version>-->
        <!--<snap.version>8.0.0-SNAPSHOT</snap.version>-->
<!--        <snap.version>7.0.0</snap.version>-->
<!--        <snap.version>8.0.9</snap.version>-->
        <snap.version>13.0.0</snap.version>
        <netbeans.version>RELEASE210</netbeans.version>
        <javahelp.version>2.0.05</javahelp.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.esa.snap</groupId>
            <artifactId>ceres-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.esa.snap</groupId>
            <artifactId>ceres-binding</artifactId>
        </dependency>
        <dependency>
            <groupId>org.esa.snap</groupId>
            <artifactId>ceres-jai</artifactId>
        </dependency>
        <dependency>
            <groupId>org.esa.snap</groupId>
            <artifactId>ceres-metadata</artifactId>
        </dependency>
        <dependency>
            <groupId>org.esa.snap</groupId>
            <artifactId>ceres-glayer</artifactId>
        </dependency>
        <dependency>
            <groupId>org.esa.snap</groupId>
            <artifactId>snap-binning</artifactId>
        </dependency>
        <dependency>
            <groupId>org.esa.snap</groupId>
            <artifactId>snap-runtime</artifactId>
        </dependency>
        <dependency>
            <groupId>org.esa.snap</groupId>
            <artifactId>snap-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.esa.snap</groupId>
            <artifactId>snap-gpf</artifactId>
        </dependency>
        <dependency>
            <groupId>org.esa.snap</groupId>
            <artifactId>snap-envisat-reader</artifactId>
        </dependency>
		<dependency>
            <groupId>org.esa.snap</groupId>
            <artifactId>snap-raster</artifactId>
        </dependency>
        <dependency>
            <groupId>org.esa.snap</groupId>
            <artifactId>snap-collocation</artifactId>
        </dependency>
        <dependency>
            <groupId>org.esa.snap</groupId>
            <artifactId>snap-netcdf</artifactId>
        </dependency>
        
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
        </dependency>

        <dependency>
            <groupId>ncsa.hdf</groupId>
            <artifactId>lib-hdf</artifactId>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.netbeans.utilities</groupId>
                <artifactId>nbm-maven-plugin</artifactId>
            </plugin>

        </plugins>
    </build>

</project>
