#!/bin/bash
# WV CCI environment setup at CEMS
# usage:  . mywvcci

export WVCCI_INST=/group_workspaces/cems2/qa4ecv/vol4/olafd/wvcci-inst
export WVCCI_LOG=$WVCCI_INST/log

export SNAP_VERSION=snap

export PYTHONPATH=$WVCCI_INST:$WVCCI_INST/src:$PYTHONPATH
export PATH=$WVCCI_INST:$WVCCI_INST/bin:$PATH

PS1="\[\e]0;\u@\h: \w\a\]\[\e[1;32m\]\u \[\e[1;34m\]\w\[\e[0m\] \[\e[0;31m\](WVCCI)\[\e[0m\]$ "

echo "using WV CCI instance $WV_INST"
